name: Deploy to Coolify

on:
  workflow_call:
    secrets:
      COOLIFY_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App to Coolify
        run: |
          curl -s -X GET \
            "https://coolify.maiyu.com.br/api/v1/deploy?uuid=kd2v2ust5csfaaa6sjsjqegk&force=false" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
            -H "Content-Type: application/json"
